# Experiment 01 : MOREPOC Data Preparation

## MSc Geography Dissertation

### Title

**Satellite-Based Estimation of Riverine Particulate Organic Carbon (POC) Using Landsat Surface Reflectance and Machine Learning**

---

## Purpose

This notebook prepares the MOREPOC global river particulate organic carbon dataset for remote sensing analysis.

The workflow includes:

- loading the MOREPOC database,
- exploring the dataset,
- cleaning missing and inconsistent records,
- preparing spatial information,
- formatting dates,
- generating sampling identifiers,
- exporting a standardized dataset for Landsat image extraction.

---

## Expected Output

A clean and standardized dataset that will serve as the input for Experiment 02 (Landsat Reflectance Extraction).

---

**Author:** Atul Kumar  
**Programme:** M.Sc. Geography  
**Institution:** Central University of Haryana

## Overall Workflow

MOREPOC Database

↓

Data Cleaning

↓

Spatial Processing

↓

Quality Assessment

↓

Export Clean Dataset

↓

Experiment 02

Landsat Surface Reflectance Extraction

↓

Experiment 03

Machine Learning Dataset Construction

↓

Experiment 04

Random Forest Aqua-OC Model

↓

Experiment 05

River POC Mapping and Analysis

# Section 2 : Objectives

## Primary Objective

To prepare a standardized and quality-controlled MOREPOC (Global River Particulate Organic Carbon) database for satellite-based estimation of riverine particulate organic carbon (POC).

---

## Specific Objectives

The objectives of this notebook are to:

1. Import and inspect the MOREPOC global database.

2. Understand the structure and attributes of the dataset.

3. Assess data quality by identifying missing values, duplicate records, and inconsistent observations.

4. Standardize temporal information by converting sampling dates into a consistent format.

5. Prepare spatial information required for remote sensing analysis by creating geographic point features.

6. Generate unique sample identifiers for traceability throughout the workflow.

7. Export a clean and standardized dataset for Landsat Surface Reflectance extraction in **Experiment 02**.

---

## Expected Outcome

At the completion of this notebook, a high-quality dataset will be available containing:

- Standardized sample information
- Geographic coordinates
- Sampling dates
- River identifiers
- Measured POC concentration
- Clean attribute table
- Spatial point dataset

This dataset will serve as the foundation for all subsequent experiments involving Landsat imagery, feature engineering, machine learning, and river POC mapping.

---

## Dissertation Relevance

Reliable machine learning models depend on high-quality input data.

Errors in coordinates, sampling dates, or attribute values directly affect:

- Landsat image matching
- Spectral feature extraction
- Model accuracy
- Prediction reliability

Therefore, systematic data preparation is a critical first step in developing a scientifically robust Aqua-OC workflow.

### Interpretation

This section establishes the scientific goals of Experiment 01. Rather than immediately processing the data, it defines the purpose of the workflow and explains why careful preparation of the MOREPOC dataset is essential. A well-prepared dataset minimizes errors in subsequent Landsat image matching and machine learning, improving the overall reliability and reproducibility of the research.

# Section 3 : MOREPOC Database Description

## Overview

The **MOREPOC (Multi-Source River Particulate Organic Carbon)** database is a global compilation of field measurements of riverine Particulate Organic Carbon (POC) collected from rivers across different climatic, hydrological, and geographical regions.

The dataset integrates measurements reported in published scientific literature and provides standardized information on river water quality, organic carbon concentration, and sampling locations.

The MOREPOC database serves as the reference (ground truth) dataset for developing remote sensing and machine learning models capable of estimating riverine POC from satellite observations.

---

## Dataset Contents

Each observation in the MOREPOC database represents one field sampling event and typically contains:

- River name
- Basin name
- Country
- Latitude
- Longitude
- Sampling date
- Measured POC concentration
- Suspended sediment concentration
- Additional geochemical variables
- Reference publication

---

## Spatial Coverage

The database contains observations from rivers distributed across multiple continents including:

- Asia
- Europe
- North America
- South America
- Africa
- Australia

This broad geographical coverage makes MOREPOC suitable for developing globally applicable machine learning models.

---

## Temporal Coverage

The observations span several decades, allowing analysis across different hydrological conditions and climatic periods.

Because Landsat imagery has been available since the 1980s, a large proportion of these observations can potentially be matched with satellite data.

---

## Role in This Research

In this dissertation, the MOREPOC database provides:

- Ground observations of riverine POC.
- Geographic locations for satellite image extraction.
- Target values for machine learning.
- Validation data for model performance assessment.

The measured POC concentration serves as the dependent variable, while Landsat-derived spectral information forms the predictor variables.

---

## Advantages of the MOREPOC Database

- Global spatial coverage.
- Literature-validated observations.
- Standardized measurement format.
- Suitable for remote sensing studies.
- Supports machine learning applications.
- Enables comparison across different river systems.

---

## Limitations

Despite its usefulness, the database has several limitations:

- Uneven spatial distribution of samples.
- Missing observations in some regions.
- Temporal mismatch between field sampling and satellite overpass.
- Variable sampling density among rivers.
- Differences in sampling methodologies across published studies.

These limitations are addressed later through quality control, temporal matching, and data preprocessing.

### Interpretation

The MOREPOC database forms the foundation of the Aqua-OC workflow because it provides reliable field measurements of riverine particulate organic carbon collected from diverse river systems worldwide. These observations act as the reference values against which Landsat-derived spectral information will be calibrated using machine learning.

Understanding the characteristics, strengths, and limitations of the dataset is essential before beginning preprocessing and image extraction, as the quality of the final predictive model depends directly on the quality and representativeness of the input data.

# Section 4 : Import Required Libraries

## Objective

This section imports all Python libraries required throughout the MOREPOC data preparation workflow.

The imported libraries support:

- Data manipulation
- Numerical computation
- Geographic data processing
- Remote sensing
- Visualization
- Statistical analysis
- Google Earth Engine interaction

Keeping all imports in a single section improves reproducibility and ensures that the computational environment is fully prepared before data processing begins.

---

## Libraries Used

| Library | Purpose |
|----------|---------|
| pandas | Data manipulation and analysis |
| numpy | Numerical computation |
| geopandas | Spatial vector data processing |
| matplotlib | Scientific plotting |
| seaborn | Statistical visualization |
| shapely | Geometry creation and manipulation |
| Earth Engine (ee) | Google Earth Engine API |
| geemap | Interactive Earth Engine visualization |
| warnings | Suppress unnecessary warnings |

---

## Dissertation Relevance

Reliable scientific analysis depends on a reproducible computational environment. Importing and documenting all required libraries at the beginning of the notebook ensures that subsequent experiments can be reproduced consistently across different computing systems.

In [12]:
# ============================================================
# Section 4 : Import Required Libraries
# ============================================================

# -----------------------------
# Data Handling
# -----------------------------
import pandas as pd
import numpy as np

# -----------------------------
# Spatial Data
# -----------------------------
import geopandas as gpd
from shapely.geometry import Point

# -----------------------------
# Visualization
# -----------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# Google Earth Engine
# -----------------------------
import ee
import geemap

# -----------------------------
# Miscellaneous
# -----------------------------
import warnings

warnings.filterwarnings("ignore")

# -----------------------------
# Display Options
# -----------------------------
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 4)

print("=" * 70)
print("Section 4 Completed")
print("=" * 70)

print("\nLibraries Imported Successfully")

print("\nPython Environment Ready")

======================================================================
Section 4 Completed
======================================================================

Libraries Imported Successfully

Python Environment Ready

### Interpretation

Successful execution of this section confirms that the Python environment has been configured correctly and that all essential libraries required for data processing, spatial analysis, visualization, and Google Earth Engine interaction are available.

This environment will be used consistently throughout the subsequent experiments, ensuring reproducibility and reducing the likelihood of package-related errors during the workflow.

# Section 5 : Google Earth Engine Initialization

## Objective

This section initializes the Google Earth Engine (GEE) Python API, which provides cloud-based access to multi-temporal satellite imagery and geospatial datasets.

Google Earth Engine serves as the primary platform for:

- Landsat Surface Reflectance retrieval
- Image preprocessing
- Cloud masking
- Spectral feature extraction
- Large-scale geospatial computation

---

## Google Earth Engine Project

**Project Name:** `oc-flux`

This project has already been configured and authenticated.

---

## Expected Output

Successful execution of this section confirms that:

- Google Earth Engine authentication is valid.
- The selected project is accessible.
- The Python environment is connected to the Earth Engine servers.
- The notebook is ready for satellite image processing.

---

## Dissertation Relevance

Google Earth Engine enables efficient processing of thousands of Landsat observations without downloading satellite imagery locally. Its cloud-computing infrastructure significantly reduces computational time while ensuring reproducibility and scalability for remote sensing research.

In [13]:
# ============================================================
# Section 5 : Initialize Google Earth Engine
# ============================================================

import ee
import geemap

# ------------------------------------------------------------
# Initialize Earth Engine
# ------------------------------------------------------------

PROJECT_NAME = "oc-flux"

try:

    ee.Initialize(project=PROJECT_NAME)

    print("=" * 70)
    print("Section 5 Completed")
    print("=" * 70)

    print("\nGoogle Earth Engine initialized successfully.")

    print("\nProject Name :", PROJECT_NAME)

except Exception as e:

    print("=" * 70)
    print("Earth Engine Initialization Failed")
    print("=" * 70)

    print(e)

======================================================================
Section 5 Completed
======================================================================

Google Earth Engine initialized successfully.

Project Name : oc-flux

### Interpretation

Successful initialization confirms that the notebook is connected to the Google Earth Engine cloud platform. This connection allows direct access to Landsat imagery and geospatial datasets without requiring local storage of satellite data.

All subsequent experiments involving image search, reflectance extraction, and spectral analysis depend on a successful Earth Engine connection. Therefore, this step acts as a prerequisite for the remote sensing workflow.

# Section 6 : Load the MOREPOC Dataset

## Objective

This section imports the MOREPOC (Multi-Source River Particulate Organic Carbon) database into the Python environment.

The dataset serves as the primary field-observation database for this dissertation and provides the reference measurements required for Landsat image matching and machine learning model development.

---

## Input

The MOREPOC dataset is stored as a CSV file containing:

- Basin information
- River names
- Geographic coordinates
- Sampling dates
- Measured particulate organic carbon (POC)
- Supporting environmental variables

---

## Expected Output

After loading the dataset, we should be able to verify:

- Number of observations
- Number of variables
- Dataset dimensions
- Successful import without errors

This confirms that the database is ready for further exploration and preprocessing.

In [14]:
# ============================================================
# Section 6 : Load Prepared MOREPOC Dataset
# ============================================================

import pandas as pd

DATA_PATH = "Indian_MOREPOC_Prepared.csv"

morepoc = pd.read_csv(DATA_PATH)

print("=" * 70)
print("Section 6 Completed")
print("=" * 70)

print("Dataset Loaded Successfully")

print("\nDataset Shape :", morepoc.shape)
print("\nRows :", morepoc.shape[0])
print("Columns :", morepoc.shape[1])

======================================================================
Section 6 Completed
======================================================================
Dataset Loaded Successfully

Dataset Shape : (66, 27)

Rows : 66
Columns : 27

### Interpretation

Successful execution of this section confirms that the MOREPOC database has been imported into the Python environment without errors.

The reported dataset dimensions provide the first indication of the volume of observations available for analysis. These observations will subsequently undergo quality assessment, preprocessing, spatial conversion, and temporal standardization before being used for Landsat image extraction and machine learning.

At this stage, no modifications have been made to the original dataset; it remains an exact copy of the source file.

# Section 7 : Dataset Overview

## Objective

Before performing any preprocessing or quality control, it is essential to understand the structure of the dataset.

This section provides a general overview of the imported MOREPOC dataset, including:

- Dataset dimensions
- Variable names
- Data types
- Sample observations
- Memory usage

Understanding the dataset structure helps identify potential data quality issues before preprocessing begins.

---

## Expected Outcome

After completing this section, we should know:

- Number of observations
- Number of variables
- Variable names
- Data types
- Overall dataset structure

No modifications are performed in this section.

In [15]:
# ============================================================
# Section 7 : Dataset Overview
# ============================================================

print("=" * 70)
print("Section 7 : Dataset Overview")
print("=" * 70)

# ------------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------------

print("\nDataset Shape")
print("-" * 40)
print(morepoc.shape)

# ------------------------------------------------------------
# Number of Rows and Columns
# ------------------------------------------------------------

print("\nNumber of Observations :", len(morepoc))
print("Number of Variables    :", len(morepoc.columns))

# ------------------------------------------------------------
# Column Names
# ------------------------------------------------------------

print("\nColumn Names")
print("-" * 40)

for i, col in enumerate(morepoc.columns, start=1):
    print(f"{i:02d}. {col}")

# ------------------------------------------------------------
# Data Types
# ------------------------------------------------------------

print("\nData Types")
print("-" * 40)

print(morepoc.dtypes)

# ------------------------------------------------------------
# Memory Usage
# ------------------------------------------------------------

print("\nMemory Usage")
print("-" * 40)

print(
    round(
        morepoc.memory_usage(deep=True).sum()/1024,
        2
    ),
    "KB"
)

# ------------------------------------------------------------
# Preview
# ------------------------------------------------------------

print("\nFirst Five Records")
print("-" * 40)

display(morepoc.head())

======================================================================
Section 7 : Dataset Overview
======================================================================

Dataset Shape
----------------------------------------
(66, 27)

Number of Observations : 66
Number of Variables    : 27

Column Names
----------------------------------------
01. bas_id
02. riv_id
03. country
04. cont
05. code
06. time_m
07. time_d
08. time_y
09. lat
10. lon
11. type_spm
12. fra_spm
13. conc_spm
14. conc_poc
15. perc_poc
16. perc_poc_1sd
17. d13C_poc
18. d13C_1sd
19. D14C_poc
20. D14C_1sd
21. age_14C
22. F14C
23. perc_tn
24. cn_ratio
25. alsi_ratio
26. ref
27. sample_date

Data Types
----------------------------------------
bas_id              str
riv_id              str
country             str
cont                str
code                str
time_m          float64
time_d          float64
time_y          float64
lat             float64
lon             float64
type_spm            str
fra_spm             str
conc_spm        float64
conc_poc        float64
perc_poc        float64
perc_poc_1sd    float64
d13C_poc        float64
d13C_1sd        float64
D14C_poc        float64
D14C_1sd        float64
age_14C         float64
F14C            float64
perc_tn         float64
cn_ratio        float64
alsi_ratio      float64
ref                 str
sample_date         str
dtype: object

Memory Usage
----------------------------------------
47.65 KB

First Five Records
----------------------------------------

,bas_id,riv_id,country,cont,code,time_m,time_d,time_y,lat,lon,type_spm,fra_spm,conc_spm,conc_poc,perc_poc,perc_poc_1sd,d13C_poc,d13C_1sd,D14C_poc,D14C_1sd,age_14C,F14C,perc_tn,cn_ratio,alsi_ratio,ref,sample_date
0,Brahmaputra,Brahmaputra,India,Asia,BR 2 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,NaN,NaN,0.46,0.03,-24.9,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.24,Galy et al. (2008),1999-10-25
1,Brahmaputra,Brahmaputra,India,Asia,BR 3 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,800.0,3.9,0.49,0.03,-24.5,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.27,Galy et al. (2008),1999-10-25
2,Brahmaputra,Brahmaputra,India,Asia,BR 4 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,1800.0,5.4,0.30,0.03,-24.7,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.23,Galy et al. (2008),1999-10-25
3,Brahmaputra,Brahmaputra,India,Asia,BR 6 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,800.0,5.9,0.74,0.03,-24.7,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.31,Galy et al. (2008),1999-10-25
4,Brahmaputra,Brahmaputra,India,Asia,BR 7 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,2500.0,5.3,0.21,0.03,-25.3,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.21,Galy et al. (2008),1999-10-25

In [17]:
# ============================================================
# Section 7.1 : Convert Sample Date
# ============================================================

morepoc["sample_date"] = pd.to_datetime(morepoc["sample_date"])

print("=" * 70)
print("Section 7.1 Completed")
print("=" * 70)

print("sample_date converted to datetime.")

print(morepoc["sample_date"].dtype)

======================================================================
Section 7.1 Completed
======================================================================
sample_date converted to datetime.
datetime64[us]

### Interpretation

This section provides a preliminary understanding of the imported MOREPOC dataset.

The reported dimensions indicate the total number of observations and variables available for analysis. Listing the variable names and their data types allows us to distinguish between numerical, categorical, and temporal attributes that will require different preprocessing techniques.

At this stage, the dataset remains unchanged. The purpose of this inspection is to familiarize ourselves with its structure before beginning data quality assessment and cleaning.

# Section 8 : Data Dictionary

## Objective

This section describes every variable contained in the Indian MOREPOC dataset.

A data dictionary provides a clear explanation of each attribute, its data type, and its scientific relevance. Proper documentation improves reproducibility and ensures that subsequent preprocessing and analysis are based on a thorough understanding of the dataset.

The variables are grouped into five categories:

- Basin and River Information
- Sampling Information
- Geographic Information
- Water Quality Measurements
- Geochemical Measurements

This section serves as the reference document for all subsequent experiments.

In [18]:
# ============================================================
# Section 8 : Variable Description
# ============================================================

data_dictionary = pd.DataFrame({

    "Variable":[
        "bas_id",
        "riv_id",
        "country",
        "cont",
        "code",
        "time_m",
        "time_d",
        "time_y",
        "lat",
        "lon",
        "type_spm",
        "fra_spm",
        "conc_spm",
        "conc_poc",
        "perc_poc",
        "perc_poc_1sd",
        "d13C_poc",
        "d13C_1sd",
        "D14C_poc",
        "D14C_1sd",
        "age_14C",
        "F14C",
        "perc_tn",
        "cn_ratio",
        "alsi_ratio",
        "ref",
        "sample_date"
    ],

    "Description":[
        "River basin name",
        "River identifier",
        "Country",
        "Continent",
        "Sampling station code",
        "Sampling month",
        "Sampling day",
        "Sampling year",
        "Latitude (decimal degrees)",
        "Longitude (decimal degrees)",
        "Suspended particulate matter type",
        "Fraction of suspended particulate matter",
        "Suspended particulate matter concentration",
        "Particulate Organic Carbon concentration",
        "Percentage of particulate organic carbon",
        "Standard deviation of POC percentage",
        "Stable carbon isotope (δ13C)",
        "Standard deviation of δ13C",
        "Radiocarbon content (Δ14C)",
        "Standard deviation of Δ14C",
        "Radiocarbon age",
        "Fraction modern carbon",
        "Total nitrogen percentage",
        "Carbon to nitrogen ratio",
        "Aluminium to silicon ratio",
        "Reference publication",
        "Standardized sampling date"
    ]

})

print("="*70)
print("Section 8 Completed")
print("="*70)

display(data_dictionary)

======================================================================
Section 8 Completed
======================================================================

        Variable                                 Description
0         bas_id                            River basin name
1         riv_id                            River identifier
2        country                                     Country
3           cont                                   Continent
4           code                       Sampling station code
5         time_m                              Sampling month
6         time_d                                Sampling day
7         time_y                               Sampling year
8            lat                  Latitude (decimal degrees)
9            lon                 Longitude (decimal degrees)
10      type_spm           Suspended particulate matter type
11       fra_spm    Fraction of suspended particulate matter
12      conc_spm  Suspended particulate matter concentration
13      conc_poc    Particulate Organic Carbon concentration
14      perc_poc    Percentage of particulate organic carbon
15  perc_poc_1sd        Standard deviation of POC percentage
16      d13C_poc                Stable carbon isotope (δ13C)
17      d13C_1sd                  Standard deviation of δ13C
18      D14C_poc                  Radiocarbon content (Δ14C)
19      D14C_1sd                  Standard deviation of Δ14C
20       age_14C                             Radiocarbon age
21          F14C                      Fraction modern carbon
22       perc_tn                   Total nitrogen percentage
23      cn_ratio                    Carbon to nitrogen ratio
24    alsi_ratio                  Aluminium to silicon ratio
25           ref                       Reference publication
26   sample_date                  Standardized sampling date

In [19]:
# ============================================================
# Section 8.1 : Dataset Variables
# ============================================================

variable_summary = pd.DataFrame({

    "Variable": morepoc.columns,
    "Data Type": morepoc.dtypes.astype(str)

})

display(variable_summary)

                  Variable       Data Type
bas_id              bas_id             str
riv_id              riv_id             str
country            country             str
cont                  cont             str
code                  code             str
time_m              time_m         float64
time_d              time_d         float64
time_y              time_y         float64
lat                    lat         float64
lon                    lon         float64
type_spm          type_spm             str
fra_spm            fra_spm             str
conc_spm          conc_spm         float64
conc_poc          conc_poc         float64
perc_poc          perc_poc         float64
perc_poc_1sd  perc_poc_1sd         float64
d13C_poc          d13C_poc         float64
d13C_1sd          d13C_1sd         float64
D14C_poc          D14C_poc         float64
D14C_1sd          D14C_1sd         float64
age_14C            age_14C         float64
F14C                  F14C         float64
perc_tn            perc_tn         float64
cn_ratio          cn_ratio         float64
alsi_ratio      alsi_ratio         float64
ref                    ref             str
sample_date    sample_date  datetime64[us]

### Interpretation

The Indian MOREPOC dataset contains **27 variables** describing river sampling locations, field observations, and geochemical measurements.

These variables can be broadly classified into:

- **Identification variables** (basin, river, country, station code)
- **Temporal variables** (sampling month, day, year, and standardized date)
- **Spatial variables** (latitude and longitude)
- **Water quality variables** (SPM and POC measurements)
- **Geochemical variables** (carbon isotopes, nitrogen content, elemental ratios)

Among these variables, **conc_poc** represents the primary response variable for this dissertation and will later be used as the target variable for machine learning modelling. Geographic coordinates and sampling dates are particularly important because they enable matching field observations with corresponding Landsat satellite imagery in subsequent experiments.

# Section 9 : Data Quality Assessment

## Objective

High-quality datasets are essential for reliable remote sensing analysis and machine learning modelling.

This section evaluates the quality of the imported MOREPOC dataset before any preprocessing is performed.

The assessment includes:

- Missing value analysis
- Duplicate record detection
- Coordinate validation
- Temporal consistency
- Invalid POC measurements
- Overall dataset completeness

No records are modified or removed in this section. The objective is to identify potential issues that will be addressed in later preprocessing steps.

---

## Expected Outcome

After completing this section, we will understand:

- Which variables contain missing values.
- Whether duplicate observations exist.
- Whether geographic coordinates are valid.
- Whether sampling dates are consistent.
- Whether the target variable (POC concentration) contains invalid values.

This assessment provides the basis for systematic data cleaning in subsequent sections.

---

## Dissertation Relevance

Data quality directly influences the accuracy of Landsat image matching and machine learning model performance. Conducting a structured quality assessment ensures that preprocessing decisions are transparent, reproducible, and scientifically justified.

In [21]:
# ============================================================
# Section 9 : Data Quality Assessment
# ============================================================

print("=" * 70)
print("Section 9 : Data Quality Assessment")
print("=" * 70)

# ------------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------------

print("\nDataset Shape")
print("-" * 40)
print(morepoc.shape)

# ------------------------------------------------------------
# Missing Values
# ------------------------------------------------------------

missing = morepoc.isnull().sum()

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage (%)": round((missing / len(morepoc)) * 100, 2)
})

print("\nMissing Values")
print("-" * 40)

display(
    missing_df.sort_values(
        "Missing Values",
        ascending=False
    )
)

# ------------------------------------------------------------
# Duplicate Records
# ------------------------------------------------------------

duplicates = morepoc.duplicated().sum()

print("\nDuplicate Records :", duplicates)

# ------------------------------------------------------------
# Duplicate Sample IDs
# ------------------------------------------------------------

if "code" in morepoc.columns:
    duplicate_codes = morepoc["code"].duplicated().sum()
    print("Duplicate Sampling Codes :", duplicate_codes)

# ------------------------------------------------------------
# Coordinate Validation
# ------------------------------------------------------------

invalid_lat = (
    (morepoc["lat"] < -90) |
    (morepoc["lat"] > 90)
).sum()

invalid_lon = (
    (morepoc["lon"] < -180) |
    (morepoc["lon"] > 180)
).sum()

print("\nInvalid Latitude :", invalid_lat)
print("Invalid Longitude:", invalid_lon)

# ------------------------------------------------------------
# Missing Coordinates
# ------------------------------------------------------------

print("\nMissing Latitude :", morepoc["lat"].isna().sum())
print("Missing Longitude:", morepoc["lon"].isna().sum())

# ------------------------------------------------------------
# Target Variable
# ------------------------------------------------------------

print("\nMissing POC Values :", morepoc["conc_poc"].isna().sum())

negative_poc = (
    morepoc["conc_poc"] < 0
).sum()

print("Negative POC Values:", negative_poc)

# ------------------------------------------------------------
# Date Check
# ------------------------------------------------------------

print("\nSample Date Range")
print("-" * 40)

print("Earliest :", morepoc["sample_date"].min())
print("Latest   :", morepoc["sample_date"].max())

print("\nSection 9 Completed Successfully")

======================================================================
Section 9 : Data Quality Assessment
======================================================================

Dataset Shape
----------------------------------------
(66, 27)

Missing Values
----------------------------------------

              Missing Values  Percentage (%)
age_14C                   66          100.00
F14C                      66          100.00
D14C_poc                  66          100.00
D14C_1sd                  66          100.00
perc_tn                   41           62.12
cn_ratio                  41           62.12
alsi_ratio                27           40.91
perc_poc_1sd              25           37.88
lon                       25           37.88
lat                       25           37.88
d13C_1sd                  25           37.88
conc_poc                  14           21.21
conc_spm                  14           21.21
type_spm                   0            0.00
time_d                     0            0.00
code                       0            0.00
cont                       0            0.00
riv_id                     0            0.00
country                    0            0.00
bas_id                     0            0.00
time_y                     0            0.00
time_m                     0            0.00
fra_spm                    0            0.00
d13C_poc                   0            0.00
perc_poc                   0            0.00
ref                        0            0.00
sample_date                0            0.00

Duplicate Records : 0
Duplicate Sampling Codes : 9

Invalid Latitude : 0
Invalid Longitude: 0

Missing Latitude : 25
Missing Longitude: 25

Missing POC Values : 14
Negative POC Values: 0

Sample Date Range
----------------------------------------
Earliest : 1997-03-15 00:00:00
Latest   : 2013-09-30 00:00:00

Section 9 Completed Successfully

### Interpretation

The quality assessment indicates that the Indian MOREPOC dataset is generally suitable for remote sensing analysis but requires careful preprocessing before Landsat image extraction and machine learning.

#### Duplicate Records

No completely duplicated records were identified, indicating that each observation represents a unique sampling event.

However, **9 duplicate sampling station codes** were detected. This is expected because the same sampling station may have been visited on different dates or under different hydrological conditions. These records should not be removed unless both the sampling date and measurements are identical.

#### Geographic Coordinates

No invalid latitude or longitude values were found, confirming that all available coordinates lie within valid geographic ranges.

However, **25 observations lack geographic coordinates**. Since satellite image extraction requires precise sampling locations, these observations cannot be linked with Landsat imagery unless their coordinates can be recovered from the original publications or supplementary datasets.

#### Particulate Organic Carbon (POC)

The target variable (`conc_poc`) contains **14 missing observations**. These records cannot be used for supervised machine learning because the response variable is unavailable.

Importantly, **no negative POC concentrations** were identified, indicating that all recorded POC values are physically meaningful.

#### Temporal Coverage

Sampling dates range from **15 March 1997** to **30 September 2013**, providing approximately sixteen years of field observations.

This temporal coverage overlaps well with the Landsat archive, making the dataset suitable for satellite-based analysis.

#### Overall Assessment

The dataset contains reliable observations but requires preprocessing before further analysis. The primary issues identified are:

- Missing geographic coordinates (25 samples)
- Missing POC concentrations (14 samples)
- Repeated station identifiers associated with different sampling events

These issues will be addressed systematically during the preprocessing stage in the following sections.

# Section 10 : Exploratory Data Analysis (EDA)

## Objective

Exploratory Data Analysis (EDA) is performed to understand the statistical characteristics, spatial distribution, and temporal coverage of the Indian MOREPOC dataset.

EDA helps identify:

- Distribution of POC concentrations
- Sampling intensity
- Spatial coverage
- Temporal coverage
- Potential outliers
- Relationships among variables

Understanding these characteristics provides valuable insight before data preprocessing and machine learning.

---

## Expected Outcomes

After completing this section, we will understand:

- Distribution of POC measurements
- Distribution of suspended sediment concentration
- Sampling frequency through time
- River-wise sampling intensity
- Spatial distribution of observations
- Relationships among numerical variables

These analyses support informed preprocessing and model development.

In [24]:
# ============================================================
# Section 10.1 : Summary Statistics
# ============================================================

print("=" * 70)
print("Section 10.1 : Summary Statistics")
print("=" * 70)

summary = morepoc.describe().T

display(summary)

======================================================================
Section 10.1 : Summary Statistics
======================================================================

,count,mean,min,25%,50%,75%,max,std
time_m,66.0,7.1667,3.0,6.0,7.0,8.0,10.0,1.4313
time_d,66.0,20.697,5.0,10.0,25.0,30.0,31.0,9.8855
time_y,66.0,2005.5152,1997.0,2001.0,2001.0,2013.0,2013.0,6.0466
lat,41.0,25.9773,25.3,25.62,26.02,26.19,27.74,0.6025
lon,41.0,88.268,83.01,85.15,87.6,91.74,94.26,3.4597
conc_spm,52.0,759.9135,0.4,11.375,135.55,1100.0,5300.0,1161.3709
conc_poc,52.0,3.9019,0.0,0.6,2.9,5.9,14.5,3.8511
perc_poc,66.0,2.9435,0.14,0.4675,0.755,5.39,11.64,3.3191
perc_poc_1sd,41.0,0.05,0.03,0.03,0.03,0.03,0.76,0.1145
d13C_poc,66.0,-25.0197,-32.1,-26.7,-25.1,-23.5,-21.2,2.2521
d13C_1sd,41.0,0.2427,0.1,0.25,0.25,0.25,0.25,0.0327
D14C_poc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D14C_1sd,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age_14C,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F14C,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
perc_tn,25.0,0.836,0.33,0.72,0.83,0.97,1.31,0.2398
cn_ratio,25.0,8.02,4.0,6.4,7.6,9.6,12.9,2.1785
alsi_ratio,39.0,0.2456,0.1,0.21,0.25,0.29,0.38,0.0618
sample_date,66,2006-01-30 06:32:43.636363,1997-03-15 00:00:00,2001-07-26 12:00:00,2001-08-10 00:00:00,2013-06-30 00:00:00,2013-09-30 00:00:00,NaN

# Section 11 : Data Cleaning & Preprocessing

## Objective

The purpose of this section is to prepare the Indian MOREPOC dataset for remote sensing analysis while preserving as much valuable field information as possible.

Unlike conventional cleaning approaches that remove all incomplete observations, this workflow retains samples with missing geographic coordinates because these coordinates may be recovered later from original publications or supplementary metadata.

The preprocessing includes:

1. Remove observations with missing target variable (conc_poc)
2. Preserve observations with missing coordinates
3. Create a coordinate availability flag
4. Standardize date format
5. Create unique sample identifiers
6. Save the cleaned dataset

This approach maximizes data retention while ensuring transparency throughout the preprocessing workflow.

In [32]:
# ============================================================
# Section 11.1 : Create Working Copy
# ============================================================

clean_df = morepoc.copy()

print("="*70)
print("Working Copy Created")
print("="*70)

print(clean_df.shape)

======================================================================
Working Copy Created
======================================================================
(66, 27)

In [33]:
# ============================================================
# Section 11.2 : Remove Missing POC
# ============================================================

before = len(clean_df)

clean_df = clean_df.dropna(subset=["conc_poc"])

after = len(clean_df)

print("="*70)
print("Missing Target Variable")
print("="*70)

print("Before :", before)
print("After  :", after)
print("Removed:", before-after)

======================================================================
Missing Target Variable
======================================================================
Before : 66
After  : 52
Removed: 14

In [34]:
# ============================================================
# Section 11.3 : Coordinate Status
# ============================================================

clean_df["coordinate_status"] = np.where(

    clean_df["lat"].isna() |
    clean_df["lon"].isna(),

    "Missing",

    "Available"

)

print("="*70)
print("Coordinate Availability")
print("="*70)

print(clean_df["coordinate_status"].value_counts())

======================================================================
Coordinate Availability
======================================================================
coordinate_status
Available    27
Missing      25
Name: count, dtype: int64

In [35]:
# ============================================================
# Section 11.4 : Sample ID
# ============================================================

clean_df = clean_df.reset_index(drop=True)

clean_df["sample_id"] = [

    f"IND_{i+1:04d}"

    for i in range(len(clean_df))

]

display(

clean_df[
    [
        "sample_id",
        "riv_id",
        "sample_date",
        "coordinate_status"
    ]
].head()

)

  sample_id        riv_id sample_date coordinate_status
0  IND_0001  Brahmaputra   1999-10-25         Available
1  IND_0002  Brahmaputra   1999-10-25         Available
2  IND_0003  Brahmaputra   1999-10-25         Available
3  IND_0004  Brahmaputra   1999-10-25         Available
4  IND_0005  Brahmaputra   1999-10-25         Available

In [36]:
# ============================================================
# Section 11.5 : Date
# ============================================================

clean_df["sample_date"] = pd.to_datetime(
    clean_df["sample_date"]
)

print(clean_df["sample_date"].dtype)

datetime64[us]

In [37]:
# ============================================================
# Section 11.6 : Final Dataset Summary
# ============================================================

print("="*70)
print("Clean Dataset Summary")
print("="*70)

print("Rows :", len(clean_df))
print("Columns :", len(clean_df.columns))

print("\nCoordinate Status")

print(clean_df["coordinate_status"].value_counts())

display(clean_df.head())

======================================================================
Clean Dataset Summary
======================================================================
Rows : 52
Columns : 29

Coordinate Status
coordinate_status
Available    27
Missing      25
Name: count, dtype: int64

,bas_id,riv_id,country,cont,code,time_m,time_d,time_y,lat,lon,type_spm,fra_spm,conc_spm,conc_poc,perc_poc,perc_poc_1sd,d13C_poc,d13C_1sd,D14C_poc,D14C_1sd,age_14C,F14C,perc_tn,cn_ratio,alsi_ratio,ref,sample_date,coordinate_status,sample_id
0,Brahmaputra,Brahmaputra,India,Asia,BR 3 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,800.0,3.9,0.49,0.03,-24.5,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.27,Galy et al. (2008),1999-10-25,Available,IND_0001
1,Brahmaputra,Brahmaputra,India,Asia,BR 4 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,1800.0,5.4,0.30,0.03,-24.7,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.23,Galy et al. (2008),1999-10-25,Available,IND_0002
2,Brahmaputra,Brahmaputra,India,Asia,BR 6 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,800.0,5.9,0.74,0.03,-24.7,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.31,Galy et al. (2008),1999-10-25,Available,IND_0003
3,Brahmaputra,Brahmaputra,India,Asia,BR 7 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,2500.0,5.3,0.21,0.03,-25.3,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.21,Galy et al. (2008),1999-10-25,Available,IND_0004
4,Brahmaputra,Brahmaputra,India,Asia,BR 8 Brahmaputra-Guwahati,10.0,25.0,1999.0,26.19,91.74,PSD,Bulk,1200.0,5.5,0.46,0.03,-25.5,0.25,NaN,NaN,NaN,NaN,NaN,NaN,0.25,Galy et al. (2008),1999-10-25,Available,IND_0005

In [38]:
# ============================================================
# Section 11.7 : Save
# ============================================================

clean_df.to_csv(

    "Indian_MOREPOC_Prepared.csv",

    index=False

)

print("="*70)
print("Dataset Saved Successfully")
print("="*70)

print("Indian_MOREPOC_Prepared.csv")

======================================================================
Dataset Saved Successfully
======================================================================
Indian_MOREPOC_Prepared.csv

In [43]:
gee_input = clean_df[
    clean_df["coordinate_status"] == "Available"
].copy()

print(gee_input.shape)

gee_input.to_csv(
    "Indian_MOREPOC_GEE_Input.csv",
    index=False
)

(27, 29)

In [46]:
gee_input = clean_df[
    clean_df["coordinate_status"] == "Available"
].copy()

missing_coordinates = clean_df[
    clean_df["coordinate_status"] == "Missing"
].copy()

gee_input.to_csv(
    "Indian_MOREPOC_GEE_Input.csv",
    index=False
)

missing_coordinates.to_csv(
    "Indian_MOREPOC_MissingCoordinates.csv",
    index=False
)

In [47]:
print(clean_df.shape)

gee_input = clean_df[
    clean_df["coordinate_status"] == "Available"
].copy()

missing_coordinates = clean_df[
    clean_df["coordinate_status"] == "Missing"
].copy()

print("GEE Input:", gee_input.shape)
print("Missing Coordinates:", missing_coordinates.shape)

(52, 29)
GEE Input: (27, 29)
Missing Coordinates: (25, 29)

In [49]:
import os

print(os.getcwd())

print(os.listdir())

C:\Users\Dell\Aqua_OC_India\notebooks\DATA AUDITING FOR ML MODEL
['.ipynb_checkpoints', '01_MOREPOC_Data_Exploration.ipynb', '02_MOREPOC_GEE_Extraction_Optimized.ipynb', '02_MOREPOC_Landsat_Rebuilt.ipynb', '03_Missing_Reflectance_GEE_Extraction.ipynb', 'Experiment_01_MOREPOC_Data_Preparation.ipynb', 'Indian_MOREPOC.csv', 'Indian_MOREPOC.geojson', 'Indian_MOREPOC_GEE_Input.csv', 'Indian_MOREPOC_Landsat_Assigned.csv', 'Indian_MOREPOC_MissingCoordinates.csv', 'Indian_MOREPOC_Prepared.csv', 'Intermediate', 'MOREPOC_Downloads', 'MOREPOC_GEE_Input_Global.csv', 'MOREPOC_Global_model_dataset.csv', 'MOREPOC_Global_Sampling_Locations.geojson', 'MOREPOC_Global_Training_Dataset.csv', 'RandomForest_POC_Log_Model.pkl', 'RandomForest_POC_Model.pkl', 'Untitled.ipynb']

In [48]:
gee_input.to_csv(
    "Indian_MOREPOC_GEE_Input.csv",
    index=False
)

missing_coordinates.to_csv(
    "Indian_MOREPOC_MissingCoordinates.csv",
    index=False
)

print("Files Saved Successfully")

Files Saved Successfully

### Interpretation

The preprocessing stage retained all observations with valid POC measurements while preserving samples that currently lack geographic coordinates.

Only observations with missing target values (`conc_poc`) were removed because supervised machine learning requires known response variables.

Instead of deleting observations with missing coordinates, a new variable (`coordinate_status`) was introduced to distinguish between samples that are immediately suitable for satellite image extraction and those requiring future coordinate recovery.

This strategy maximizes data retention, improves reproducibility, and prevents the unnecessary loss of valuable field observations.

The cleaned dataset will serve as the master dataset for the remaining experiments, while only observations with available coordinates will be used for Landsat image extraction.